name: Go test

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: pwd
          MONGO_INITDB_DATABASE: sundae
        volumes:
          - $PWD/.github/workflows/init_mongo_test.js:/docker-entrypoint-initdb.d/init.js

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.13"

      - name: Install make
        run: |
          sudo apt update && \
          sudo apt install -y make

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install go protoc
        run: |
          go get -v \
          google.golang.org/protobuf/cmd/protoc-gen-go \
          google.golang.org/grpc/cmd/protoc-gen-go-grpc

      - name: setup env
        run: |
          echo "name=GOPATH::$(go env GOPATH)" >> $GITHUB_ENV
          echo "name=GOPATH::$PATH:$(go env GOPATH)/bin" >> $GITHUB_ENV
        shell: bash

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: make

      - name: Test
        run: make go_test
