name: Go test

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: pwd
          MONGO_INITDB_DATABASE: sundae
        volumes:
          - "init_mongo_test.js:/docker-entrypoint-initdb.d/init.js"

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Install make and unzip
        run: |
          sudo apt update && \
          sudo apt install -y make unzip

      - name: Install protobuf-compiler
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.13.0/protoc-3.13.0-linux-x86_64.zip
          unzip protoc-3.13.0-linux-x86_64.zip -d $HOME/.local
          echo "name=PATH::$PATH:$HOME/.local/bin"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install go protoc
        run: |
          go get -v \
          google.golang.org/protobuf/cmd/protoc-gen-go \
          google.golang.org/grpc/cmd/protoc-gen-go-grpc

      - name: setup env
        run: |
          echo "name=GOPATH::$(go env GOPATH)" >> $GITHUB_ENV
          echo "name=GOPATH::$PATH:$(go env GOPATH)/bin" >> $GITHUB_ENV
        shell: bash

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: make

      - name: Test
        run: make go_test
